version: '3'
services:
  app:
    build: .
    ports:
      - 8080:8080
    container_name: sample_app
    volumes:
      - ./:/go
    tty: true
    restart: always
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    volumes:
      - mysqldata:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_as_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306
volumes:
  mysqldata:
    driver: local
